services:
  stats-server:
    build:
      dockerfile: stats/stats-server/Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/postgres

  stats-db:
    image: postgres:16.1
    environment:
      POSTGRES_PASSWORD: password
#    ports:
#      - "5432:5432"


#  ewm-service:
#    ports:
#      - "8080:8080"
#
#  ewm-db:
#    image: postgres:16.1
